import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    cli: 'src/cli.ts',
    index: 'src/index.ts',
  },
  format: ['esm'],
  target: 'node20',
  platform: 'node',
  sourcemap: true,
  clean: true,
  splitting: false,
  dts: false,
  external: ['ink', 'react', 'react/jsx-runtime'],
  noExternal: [],
  banner: {
    js: `/* deepcode - generated by tsup */`,
  },
});
