// deepcode public API (for secondary development / plugin consumption)
export { DeepcodeEngine, providerLabel } from './engine.js';
export type { EngineOptions } from './engine.js';
export type { EngineEvent, EngineEventSink } from './events.js';
export { loadConfig } from './config/loader.js';
export type { ResolvedConfig, ResolvedPaths } from './config/loader.js';
export { defaultConfig, mergeConfig, modelMetaFor, pricingFor, BUILTIN_MODEL_META } from './config/defaults.js';
export type { DeepcodeConfig, ModelMeta, ProviderId, PermissionMode } from './config/types.js';
export type { LLMProvider, LLMRequest, LLMResponse, LLMStreamEvent, ChatMessage, ToolSchema, Usage } from './providers/types.js';
export { createProvider } from './providers/factory.js';
export type { ToolDef, ToolContext, ToolResult, ToolPreview } from './tools/types.js';
export { ToolRegistry } from './tools/registry.js';
export { ToolExecutor } from './tools/executor.js';
export { PermissionGate, riskOf } from './tools/permission.js';
export type { ApprovalItem, ApprovalDecision, ApprovalResult } from './tools/permission.js';
export { runAgentTurn } from './agent/loop.js';
export { buildSystemPrompt } from './agent/system-prompt.js';
export { compressMessages } from './agent/compressor.js';
export type { CompactionPlan } from './agent/compressor.js';
export { planBreakpoints } from './caching/breakpoint-planner.js';
export { cacheHitRate, cacheSavingsUsd, aggregateCacheHitRate } from './caching/metrics.js';
export { UsageTracker } from './usage/extractor.js';
export type { UsageEvent, UsageTotals } from './usage/extractor.js';
export { estimateCostUsd } from './usage/pricing.js';
export { SessionStore } from './session/store.js';
export type { SessionRecord } from './session/types.js';
export { SkillLoader, skillsCatalog, parseSkillFile } from './skills/loader.js';
export type { Skill } from './skills/types.js';
export { PluginLoader } from './plugins/loader.js';
export type { Plugin } from './plugins/types.js';
